version: "3.8"
services:
  team_a:
    build:
      context: .
    container_name: Team_A
    networks:
      mybridgenet:
        ipv4_address: 172.19.0.2

  team_b:
    build:
      context: .
    container_name: Team_B
    networks:
      mybridgenet:
        ipv4_address: 172.19.0.3

networks:
  mybridgenet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
